### ISSUE TITLE
Accept applicants for cohort 3

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hack-camp#88] opened 2015-06-20 01:30 UTC
Third cohort will be taking place from July 13th - July 24th.

@jonleung how many people should we accept for this?

**Comment by jonleung** [comment] 2015-06-24 15:37
@zachlatta lets discuss at meeting today!

**Comment by zachlatta** [comment] 2015-06-24 19:20
Can you make sure to schedule this? I don't see anything on my calendar.

**Comment by jonleung** [comment] 2015-06-26 15:43
Closing because it is a duplicate of the active task #91

**Closed as completed by jonleung** 2015-06-26 15:43 UTC
Labels: cohort-3
