### ISSUE TITLE
Ashley

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#70] opened 2015-06-17 16:06 UTC
- read q
- read thorough own notes
- Look through GWC
- funcs
- you have lots if project time
- testing knowledge 
- training how?
- idea of tutting everything
- lack of motivation in beginning

**Comment by maxwofford** [comment] 2015-06-17 16:13
This is a duplicate of https://github.com/hackedu/hackedu/issues/29

**Closed as completed** 2015-06-17 16:12 UTC
