### ISSUE TITLE
Create day to day curriculum timeline for three weeks

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#80] opened 2015-06-18 20:58 UTC
Create a bullet point list of topics covered and deliverables for each day for the course of the three weeks.

**Comment by maxwofford** [comment] 2015-06-19 00:49
@jonleung Maybe this should only be for 2 weeks, and we let them explore on the last week?

**Comment by andreadeng** [comment] 2015-06-19 16:12
this is a duplicate of #69. Closing.

**Closed as completed by andreadeng** 2015-06-19 16:12 UTC
